//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WCF_TEST.SinhVienService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="SinhVienService.ISinhVien")]
    public interface ISinhVien {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISinhVien/getData", ReplyAction="http://tempuri.org/ISinhVien/getDataResponse")]
        System.Data.DataTable getData(string proc, string param);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISinhVien/getData", ReplyAction="http://tempuri.org/ISinhVien/getDataResponse")]
        System.Threading.Tasks.Task<System.Data.DataTable> getDataAsync(string proc, string param);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISinhVien/getData2", ReplyAction="http://tempuri.org/ISinhVien/getData2Response")]
        System.Data.DataTable getData2(string proc);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISinhVien/getData2", ReplyAction="http://tempuri.org/ISinhVien/getData2Response")]
        System.Threading.Tasks.Task<System.Data.DataTable> getData2Async(string proc);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ISinhVienChannel : WCF_TEST.SinhVienService.ISinhVien, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class SinhVienClient : System.ServiceModel.ClientBase<WCF_TEST.SinhVienService.ISinhVien>, WCF_TEST.SinhVienService.ISinhVien {
        
        public SinhVienClient() {
        }
        
        public SinhVienClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public SinhVienClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SinhVienClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SinhVienClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public System.Data.DataTable getData(string proc, string param) {
            return base.Channel.getData(proc, param);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataTable> getDataAsync(string proc, string param) {
            return base.Channel.getDataAsync(proc, param);
        }
        
        public System.Data.DataTable getData2(string proc) {
            return base.Channel.getData2(proc);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataTable> getData2Async(string proc) {
            return base.Channel.getData2Async(proc);
        }
    }
}
